baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Austin Maddison'

[params]
  author_name = 'Austin J. Maddison'
  author_name_th = 'ออสติน เจตัริน เมดดิสัน'

  [[params.links]]
    title = 'Github'
    href = 'https://github.com/AustinMaddison'
    
  [[params.links]]
    title = 'YouTube'
    href = 'https://github.com/AustinMaddison'


  [[params.links]]
    title = 'Behance'
    href = 'https://github.com/AustinMaddison'

  [[params.links]]
    title = 'RSS'
    href = 'https://github.com/AustinMaddison'

  [[params.links]]
    title = '@'
    href = 'mailto:austin.mad.th@gmail.com'



[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
