baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Austin Maddison'

[params]
  author_name = 'AUSTIN JETRIN MADDISON'
  author_name_th = 'ออสติน เจตัริน เมดดิสัน'
  author_img = "img/profile.png"
  site_icon = "img/icon.png"
  site_bg = "img/bg-abberation.png"

  [[params.links]]
    title = 'Github'
    href = 'https://github.com/AustinMaddison'
    
  [[params.links]]
    title = 'YouTube'
    href = 'https://github.com/AustinMaddison'

  [[params.links]]
    title = 'Behance'
    href = 'https://github.com/AustinMaddison'

  [[params.links]]
    title = '@'
    href = 'mailto:austin.mad.th@gmail.com'



[markup]
  [markup.highlight]
    noClasses = false
  
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 1  # Include <h1> headings
  
  [markup.goldmark.extensions]
    [markup.goldmark.extensions.passthrough]
      enable = true
      [markup.goldmark.extensions.passthrough.delimiters]
        block = [['\[', '\]'], ['$$', '$$']]
        inline = [['\(', '\)']]