[highlight]
    noClasses = false

[tableOfContents]
    startLevel = 1
    endLevel = 2


[goldmark]
    [goldmark.renderer]
        unsafe = true
    [goldmark.extensions]
        [goldmark.extensions.passthrough]
            enable = true
                [goldmark.extensions.passthrough.delimiters]
                    block = [['\[', '\]'], ['$$', '$$']]
                    inline = [['\(', '\)']]